import { mkdir, writeFile, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { units, timeline } from '../src/content.mjs';
import { unitsEn, timelineEn } from '../src/english.mjs';
import { unitsEs, timelineEs } from '../src/spanish.mjs';
import { layout, eyebrow, button, arrow, globe, photo, brandArtwork, route } from '../src/components.mjs';

const out = new URL('../dist/', import.meta.url);
await mkdir(out, { recursive: true });
await cp(new URL('../public/', import.meta.url), out, { recursive: true });
async function page(path, html) {
  const folder = new URL(`.${path}`, out);
  await mkdir(folder, { recursive: true });
  await writeFile(new URL('index.html', folder), html);
}

const unitVisual = (unit, hero = false) => unit.brandCard ? brandArtwork(hero ? unit.brandHero : unit.brandCard, unit.brandAlt, hero) : photo(unit.image, unit.alt, { hero });
const unitCard = (unit, locale = 'pt') => `<article class="unit-card reveal unit-${unit.slug}"><a class="unit-card-link" href="${route(`/${unit.slug}/`, locale)}"><div class="unit-image${unit.brandCard ? ' unit-image-logo' : ''}">${unitVisual(unit)}<span class="image-index">${unit.number} / GLOBALK GROUP</span></div><div class="unit-caption"><div><span class="small-label">${unit.category}</span><h3>${unit.name}</h3></div><span class="unit-caption-arrow" aria-hidden="true">${arrow(true)}</span></div><p>${unit.summary}</p></a></article>`;
const heroHeadline = (locale = 'pt') => {
  const english = locale === 'en';
  const spanish = locale === 'es';
  const words = english ? ['brands.', 'products.', 'people.', 'markets.'] : spanish ? ['marcas.', 'productos.', 'personas.', 'mercados.'] : ['marcas.', 'produtos.', 'pessoas.', 'mercados.'];
  const label = english ? 'We connect brands, products, people and markets.' : spanish ? 'Conectamos marcas, productos, personas y mercados.' : 'Conectamos marcas, produtos, pessoas e mercados.';
  return `<h1 class="hero-title" id="hero-title" aria-label="${label}"><span class="hero-title-intro">${english ? 'We connect' : 'Conectamos'}</span><span class="hero-rotator" aria-hidden="true">${words.map(word => `<em class="hero-word">${word}</em>`).join('')}</span></h1>`;
};

const home = `
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy">${eyebrow('Conexões globais. Presença local.')}${heroHeadline('pt')}<p class="hero-lead">Marcas, produtos e operações.<br>Uma estrutura local que abre caminhos no mercado brasileiro.</p><div class="hero-actions">${button('Explore nossas unidades', '#unidades')}${button('Conheça o grupo', '#grupo', true)}</div></div><div class="hero-art">${globe()}<div class="art-coordinate"><span class="status-dot"></span> BASE NO BRASIL. VISÃO GLOBAL.</div><span class="art-label" aria-hidden="true">CONEXÃO<br>EM MOVIMENTO</span></div><div class="hero-bottom"><span>SOROCABA, SÃO PAULO · BRASIL</span><a href="#grupo">CONTINUE EXPLORANDO <span aria-hidden="true">↓</span></a></div></section>

<section class="group-section section" id="grupo"><div class="wrap">${eyebrow('O grupo', '01')}<div class="group-grid"><h2 class="display reveal">Diferentes negócios.<br>Uma mesma vontade<br>de <em>ir além.</em></h2><div class="group-copy reveal"><p>A GlobalK reúne negócios que conectam marcas, produtos e pessoas. Da entrada no mercado brasileiro às soluções que fazem parte do dia a dia.</p><p>Com base em Sorocaba, integramos experiência comercial, desenvolvimento de produtos e operação local para abrir novos caminhos.</p><a class="text-link" href="/our-history/">Conheça nossa trajetória ${arrow(true)}</a></div></div><div class="group-ledger"><div><span class="small-label">NOSSA BASE</span><span>Sorocaba, Brasil</span></div><div><span class="small-label">NOSSA VISÃO</span><span>Conectar possibilidades</span></div><div><span class="small-label">NOSSA ATUAÇÃO</span><span>Marcas, produtos e operações</span></div></div></div></section>

<section class="units-section section" id="unidades"><div class="wrap"><div class="section-heading">${eyebrow('Unidades de negócio', '02')}<div class="section-heading-row"><h2 class="display reveal">Um grupo.<br>Muitas <em>possibilidades.</em></h2><p>Cada unidade tem seu foco.<br>Todas compartilham a vontade de fazer acontecer.</p></div></div>
<article class="unit-feature reveal"><div class="unit-feature-grid"><div class="feature-art">${photo('tradek', 'Contêineres em uma operação logística internacional', { sizes: '(min-width: 960px) 46vw, 100vw' })}<span class="image-index">01 / GLOBALK GROUP</span><span class="feature-art-label">BRASIL <span aria-hidden="true">↔</span> MUNDO</span></div><div class="feature-copy"><span class="small-label">ENTRADA NO MERCADO BRASILEIRO</span><h3>GlobalK</h3><p>Uma estrutura local.<br>Um mundo de oportunidades.</p><span class="feature-description">Da chegada ao Brasil à operação: distribuição, vendas e suporte para marcas internacionais.</span>${button('Conheça a operação', '/globalk/')}</div></div></article>
<div class="units-grid">${units.slice(1).map(unit => unitCard(unit, 'pt')).join('')}</div></div></section>

<section class="history-preview section"><div class="wrap history-preview-grid"><div>${eyebrow('Nossa trajetória', '03')}<h2 class="display reveal">O futuro tem<br>uma <em>história.</em></h2><p>Uma trajetória feita de conexões, novas marcas e oportunidades que se transformam em negócios.</p><a class="text-link" href="/our-history/">Explore nossa história ${arrow(true)}</a></div><div class="history-preview-dates reveal">${[timeline[0], timeline[4], timeline[6]].map(item => `<div><span class="history-year">${item.year}</span><p>${item.title}</p></div>`).join('')}</div></div></section>

<section class="statement-strip" aria-label="Nossa visão"><div class="wrap"><span class="small-label">A PRÓXIMA CONEXÃO PODE SER A SUA.</span><p>Possibilidades não têm <em>fronteiras.</em></p><a href="#contato" class="statement-arrow" aria-label="Converse com a GlobalK">${arrow(true)}</a></div></section>`;
await page('/', layout({ title: 'GlobalK — Conexões que abrem possibilidades', description: 'Marcas, produtos e operações conectados ao mercado brasileiro. Conheça a GlobalK, Economize, Multi-K, Safe-K e Trade-K.', content: home }));

for (const unit of units) {
  const next = units[(units.indexOf(unit) + 1) % units.length];
  const content = `<section class="unit-hero wrap"><nav class="breadcrumbs" aria-label="Caminho da página"><a href="/">Início</a><span aria-hidden="true">/</span><a href="/#unidades">Unidades</a><span aria-hidden="true">/</span><span aria-current="page">${unit.name}</span></nav><div class="unit-hero-grid"><div class="unit-hero-copy">${eyebrow(unit.category, unit.number)}<h1 class="display">${unit.title}</h1><p class="unit-lead">${unit.description}</p><div class="hero-actions">${button(unit.contactLabel, '#contato')}${unit.external ? button(unit.externalLabel, unit.external, true, true) : ''}</div><div class="unit-audience"><span class="small-label">PARA QUEM É</span><p>${unit.audience}</p></div></div><figure class="unit-hero-media${unit.brandHero ? ' logo-media' : ''}">${unitVisual(unit, true)}<figcaption><span>${unit.name}</span><span>${unit.imageCaption}</span></figcaption></figure></div></section>
  <section class="unit-services section" id="solucoes"><div class="wrap services-grid"><div class="services-intro">${eyebrow(unit.slug === 'safek' ? 'Como funciona' : 'O que fazemos')}<h2 class="display reveal">${unit.heading}</h2><p>${unit.intro}</p></div><ol class="service-list">${unit.services.map(([title, text], i) => `<li class="reveal"><span class="service-number">0${i + 1}</span><div><h3>${title}</h3><p>${text}</p></div></li>`).join('')}</ol></div>${unit.secondaryImage ? `<figure class="detail-photo wrap reveal">${photo(unit.secondaryImage, unit.secondaryAlt, { sizes: '(min-width: 960px) 80vw, 100vw' })}<figcaption>${unit.secondaryAlt}</figcaption></figure>` : ''}</section>
  <section class="unit-cta section"><div class="wrap">${eyebrow('Encontre sua próxima possibilidade')}<h2 class="display reveal">${unit.cta}</h2>${button(unit.contactLabel, '#contato')}</div></section>
  <aside class="next-unit wrap"><span class="small-label">CONTINUE EXPLORANDO O GRUPO</span><a href="/${next.slug}/"><span>${next.name}<small>${next.category}</small></span>${arrow(true)}</a></aside>`;
  await page(`/${unit.slug}/`, layout({ title: `${unit.name} — ${unit.category} | GlobalK`, description: unit.seo, path: `/${unit.slug}/`, current: unit.slug, content }));
}

const historyContent = `<section class="history-hero wrap"><nav class="breadcrumbs" aria-label="Caminho da página"><a href="/">Início</a><span aria-hidden="true">/</span><span aria-current="page">Nossa história</span></nav>${eyebrow('Nossa trajetória')}<h1 class="display">Novos caminhos.<br>A mesma vontade de <em>conectar.</em></h1><p>Cada etapa abriu espaço para a próxima. Conheça os marcos que construíram a GlobalK e suas unidades de negócio.</p><a class="text-link" href="#trajetoria">Percorra nossa história <span aria-hidden="true">↓</span></a><div class="history-hero-mark" aria-hidden="true">2010<span>→</span>HOJE</div></section>
<section class="timeline-section section" id="trajetoria"><div class="wrap timeline-grid"><div class="timeline-intro">${eyebrow('Uma história em movimento')}<h2 class="display">Conexões que<br>se tornam<br><em>caminhos.</em></h2><p>Do desenvolvimento de marcas às novas frentes de atuação do grupo.</p></div><ol class="timeline">${timeline.map(item => `<li class="reveal"><span class="timeline-year">${item.year}</span><div><h3>${item.title}</h3><p>${item.text}</p></div></li>`).join('')}</ol></div></section><section class="statement-strip"><div class="wrap"><span class="small-label">O PRÓXIMO CAPÍTULO ESTÁ EM ABERTO.</span><p>Vamos construir o que <em>vem depois.</em></p><a href="#contato" class="statement-arrow" aria-label="Fale com a GlobalK">${arrow(true)}</a></div></section>`;
await page('/our-history/', layout({ title: 'Nossa história — Uma trajetória de conexões | GlobalK', description: 'Conheça a trajetória da GlobalK: os primeiros negócios, a atuação com marcas no Brasil e a criação da Economize, Multi-K, Safe-K e Trade-K.', path: '/our-history/', current: 'history', content: historyContent }));

const homeEn = `
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy">${eyebrow('Global connections. Local presence.')}${heroHeadline('en')}<p class="hero-lead">Brands, products and operations.<br>A local structure opening new paths in the Brazilian market.</p><div class="hero-actions">${button('Explore our units', '#unidades')}${button('Meet the group', '#grupo', true)}</div></div><div class="hero-art">${globe('main', 'en')}<div class="art-coordinate"><span class="status-dot"></span> BASED IN BRAZIL. GLOBAL OUTLOOK.</div><span class="art-label" aria-hidden="true">CONNECTIONS<br>IN MOTION</span></div><div class="hero-bottom"><span>SOROCABA, SÃO PAULO · BRAZIL</span><a href="#grupo">KEEP EXPLORING <span aria-hidden="true">↓</span></a></div></section>
<section class="group-section section" id="grupo"><div class="wrap">${eyebrow('The group', '01')}<div class="group-grid"><h2 class="display reveal">Different businesses.<br>One drive to<br><em>go further.</em></h2><div class="group-copy reveal"><p>GlobalK brings together businesses that connect brands, products and people. From entering the Brazilian market to solutions for everyday life.</p><p>Based in Sorocaba, we combine commercial experience, product development and local operations to open new paths.</p><a class="text-link" href="/en/our-history/">Discover our story ${arrow(true)}</a></div></div><div class="group-ledger"><div><span class="small-label">OUR BASE</span><span>Sorocaba, Brazil</span></div><div><span class="small-label">OUR VISION</span><span>Connecting possibilities</span></div><div><span class="small-label">WHAT WE DO</span><span>Brands, products and operations</span></div></div></div></section>
<section class="units-section section" id="unidades"><div class="wrap"><div class="section-heading">${eyebrow('Business units', '02')}<div class="section-heading-row"><h2 class="display reveal">One group.<br>Many <em>possibilities.</em></h2><p>Each unit has its own focus.<br>All share the drive to make things happen.</p></div></div><article class="unit-feature reveal"><div class="unit-feature-grid"><div class="feature-art">${photo('tradek', 'Shipping containers in an international logistics operation', { sizes: '(min-width: 960px) 46vw, 100vw' })}<span class="image-index">01 / GLOBALK GROUP</span><span class="feature-art-label">BRAZIL <span aria-hidden="true">↔</span> WORLD</span></div><div class="feature-copy"><span class="small-label">BRAZILIAN MARKET ENTRY</span><h3>GlobalK</h3><p>A local structure.<br>A world of opportunities.</p><span class="feature-description">From entering Brazil to day-to-day operations: distribution, sales and support for international brands.</span>${button('Explore the operation', '/en/globalk/')}</div></div></article><div class="units-grid">${unitsEn.slice(1).map(unit => unitCard(unit, 'en')).join('')}</div></div></section>
<section class="history-preview section"><div class="wrap history-preview-grid"><div>${eyebrow('Our story', '03')}<h2 class="display reveal">The future has<br>a <em>history.</em></h2><p>A journey of connections, new brands and opportunities that become businesses.</p><a class="text-link" href="/en/our-history/">Explore our story ${arrow(true)}</a></div><div class="history-preview-dates reveal">${[timelineEn[0], timelineEn[4], timelineEn[6]].map(item => `<div><span class="history-year">${item.year}</span><p>${item.title}</p></div>`).join('')}</div></div></section>
<section class="statement-strip" aria-label="Our vision"><div class="wrap"><span class="small-label">YOUR CONNECTION COULD BE NEXT.</span><p>Possibilities have no <em>borders.</em></p><a href="#contato" class="statement-arrow" aria-label="Talk to GlobalK">${arrow(true)}</a></div></section>`;
await page('/en/', layout({ title: 'GlobalK — Connections that open possibilities', description: 'Brands, products and operations connected to the Brazilian market. Discover GlobalK, Economize, Multi-K, Safe-K and Trade-K.', content: homeEn, locale: 'en' }));

for (const unit of unitsEn) {
  const next = unitsEn[(unitsEn.indexOf(unit) + 1) % unitsEn.length];
  const content = `<section class="unit-hero wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/en/">Home</a><span aria-hidden="true">/</span><a href="/en/#unidades">Units</a><span aria-hidden="true">/</span><span aria-current="page">${unit.name}</span></nav><div class="unit-hero-grid"><div class="unit-hero-copy">${eyebrow(unit.category, unit.number)}<h1 class="display">${unit.title}</h1><p class="unit-lead">${unit.description}</p><div class="hero-actions">${button(unit.contactLabel, '#contato')}${unit.external ? button(unit.externalLabel, unit.external, true, true, 'en') : ''}</div><div class="unit-audience"><span class="small-label">WHO IT’S FOR</span><p>${unit.audience}</p></div></div><figure class="unit-hero-media${unit.brandHero ? ' logo-media' : ''}">${unitVisual(unit, true)}<figcaption><span>${unit.name}</span><span>${unit.imageCaption}</span></figcaption></figure></div></section>
  <section class="unit-services section" id="solucoes"><div class="wrap services-grid"><div class="services-intro">${eyebrow(unit.slug === 'safek' ? 'How it works' : 'What we do')}<h2 class="display reveal">${unit.heading}</h2><p>${unit.intro}</p></div><ol class="service-list">${unit.services.map(([title, description], i) => `<li class="reveal"><span class="service-number">0${i + 1}</span><div><h3>${title}</h3><p>${description}</p></div></li>`).join('')}</ol></div>${unit.secondaryImage ? `<figure class="detail-photo wrap reveal">${photo(unit.secondaryImage, unit.secondaryAlt, { sizes: '(min-width: 960px) 80vw, 100vw' })}<figcaption>${unit.secondaryAlt}</figcaption></figure>` : ''}</section>
  <section class="unit-cta section"><div class="wrap">${eyebrow('Find your next possibility')}<h2 class="display reveal">${unit.cta}</h2>${button(unit.contactLabel, '#contato')}</div></section>
  <aside class="next-unit wrap"><span class="small-label">KEEP EXPLORING THE GROUP</span><a href="/en/${next.slug}/"><span>${next.name}<small>${next.category}</small></span>${arrow(true)}</a></aside>`;
  await page(`/en/${unit.slug}/`, layout({ title: `${unit.name} — ${unit.category} | GlobalK`, description: unit.seo, path: `/${unit.slug}/`, current: unit.slug, content, locale: 'en' }));
}

const historyContentEn = `<section class="history-hero wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/en/">Home</a><span aria-hidden="true">/</span><span aria-current="page">Our story</span></nav>${eyebrow('Our journey')}<h1 class="display">New paths.<br>The same drive to <em>connect.</em></h1><p>Each step made room for the next. Discover the milestones that shaped GlobalK and its business units.</p><a class="text-link" href="#trajetoria">Explore our story <span aria-hidden="true">↓</span></a><div class="history-hero-mark" aria-hidden="true">2010<span>→</span>TODAY</div></section>
<section class="timeline-section section" id="trajetoria"><div class="wrap timeline-grid"><div class="timeline-intro">${eyebrow('A story in motion')}<h2 class="display">Connections<br>that become<br><em>new paths.</em></h2><p>From developing brands to the group’s new areas of business.</p></div><ol class="timeline">${timelineEn.map(item => `<li class="reveal"><span class="timeline-year">${item.year}</span><div><h3>${item.title}</h3><p>${item.text}</p></div></li>`).join('')}</ol></div></section><section class="statement-strip"><div class="wrap"><span class="small-label">THE NEXT CHAPTER IS STILL OPEN.</span><p>Let’s build what <em>comes next.</em></p><a href="#contato" class="statement-arrow" aria-label="Talk to GlobalK">${arrow(true)}</a></div></section>`;
await page('/en/our-history/', layout({ title: 'Our story — A journey of connections | GlobalK', description: 'Explore GlobalK’s history, its work with brands in Brazil, and the creation of Economize, Multi-K, Safe-K and Trade-K.', path: '/our-history/', current: 'history', content: historyContentEn, locale: 'en' }));

const homeEs = `
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy">${eyebrow('Conexiones globales. Presencia local.')}${heroHeadline('es')}<p class="hero-lead">Marcas, productos y operaciones.<br>Una estructura local que abre caminos en el mercado brasileño.</p><div class="hero-actions">${button('Explorar nuestras unidades', '#unidades')}${button('Conocer el grupo', '#grupo', true)}</div></div><div class="hero-art">${globe('main', 'es')}<div class="art-coordinate"><span class="status-dot"></span> BASE EN BRASIL. VISIÓN GLOBAL.</div><span class="art-label" aria-hidden="true">CONEXIONES<br>EN MOVIMIENTO</span></div><div class="hero-bottom"><span>SOROCABA, SÃO PAULO · BRASIL</span><a href="#grupo">SEGUIR EXPLORANDO <span aria-hidden="true">↓</span></a></div></section>
<section class="group-section section" id="grupo"><div class="wrap">${eyebrow('El grupo', '01')}<div class="group-grid"><h2 class="display reveal">Negocios diferentes.<br>Una misma voluntad<br>de <em>ir más allá.</em></h2><div class="group-copy reveal"><p>GlobalK reúne negocios que conectan marcas, productos y personas. Desde la entrada al mercado brasileño hasta soluciones para la vida cotidiana.</p><p>Con base en Sorocaba, integramos experiencia comercial, desarrollo de productos y operación local para abrir nuevos caminos.</p><a class="text-link" href="/es/our-history/">Conoce nuestra trayectoria ${arrow(true)}</a></div></div><div class="group-ledger"><div><span class="small-label">NUESTRA BASE</span><span>Sorocaba, Brasil</span></div><div><span class="small-label">NUESTRA VISIÓN</span><span>Conectar posibilidades</span></div><div><span class="small-label">LO QUE HACEMOS</span><span>Marcas, productos y operaciones</span></div></div></div></section>
<section class="units-section section" id="unidades"><div class="wrap"><div class="section-heading">${eyebrow('Unidades de negocio', '02')}<div class="section-heading-row"><h2 class="display reveal">Un grupo.<br>Muchas <em>posibilidades.</em></h2><p>Cada unidad tiene su enfoque.<br>Todas comparten la voluntad de hacer que las cosas sucedan.</p></div></div><article class="unit-feature reveal"><div class="unit-feature-grid"><div class="feature-art">${photo('tradek', 'Contenedores en una operación logística internacional', { sizes: '(min-width: 960px) 46vw, 100vw' })}<span class="image-index">01 / GLOBALK GROUP</span><span class="feature-art-label">BRASIL <span aria-hidden="true">↔</span> MUNDO</span></div><div class="feature-copy"><span class="small-label">ENTRADA AL MERCADO BRASILEÑO</span><h3>GlobalK</h3><p>Una estructura local.<br>Un mundo de oportunidades.</p><span class="feature-description">Desde la llegada a Brasil hasta la operación diaria: distribución, ventas y soporte para marcas internacionales.</span>${button('Conocer la operación', '/es/globalk/')}</div></div></article><div class="units-grid">${unitsEs.slice(1).map(unit => unitCard(unit, 'es')).join('')}</div></div></section>
<section class="history-preview section"><div class="wrap history-preview-grid"><div>${eyebrow('Nuestra trayectoria', '03')}<h2 class="display reveal">El futuro tiene<br>una <em>historia.</em></h2><p>Una trayectoria de conexiones, nuevas marcas y oportunidades que se convierten en negocios.</p><a class="text-link" href="/es/our-history/">Explora nuestra historia ${arrow(true)}</a></div><div class="history-preview-dates reveal">${[timelineEs[0], timelineEs[4], timelineEs[6]].map(item => `<div><span class="history-year">${item.year}</span><p>${item.title}</p></div>`).join('')}</div></div></section>
<section class="statement-strip" aria-label="Nuestra visión"><div class="wrap"><span class="small-label">LA PRÓXIMA CONEXIÓN PUEDE SER LA TUYA.</span><p>Las posibilidades no tienen <em>fronteras.</em></p><a href="#contato" class="statement-arrow" aria-label="Hablar con GlobalK">${arrow(true)}</a></div></section>`;
await page('/es/', layout({ title: 'GlobalK — Conexiones que abren posibilidades', description: 'Marcas, productos y operaciones conectados con el mercado brasileño. Conoce GlobalK, Economize, Multi-K, Safe-K y Trade-K.', content: homeEs, locale: 'es' }));

for (const unit of unitsEs) {
  const next = unitsEs[(unitsEs.indexOf(unit) + 1) % unitsEs.length];
  const content = `<section class="unit-hero wrap"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/es/">Inicio</a><span aria-hidden="true">/</span><a href="/es/#unidades">Unidades</a><span aria-hidden="true">/</span><span aria-current="page">${unit.name}</span></nav><div class="unit-hero-grid"><div class="unit-hero-copy">${eyebrow(unit.category, unit.number)}<h1 class="display">${unit.title}</h1><p class="unit-lead">${unit.description}</p><div class="hero-actions">${button(unit.contactLabel, '#contato')}${unit.external ? button(unit.externalLabel, unit.external, true, true, 'es') : ''}</div><div class="unit-audience"><span class="small-label">PARA QUIÉN ES</span><p>${unit.audience}</p></div></div><figure class="unit-hero-media${unit.brandHero ? ' logo-media' : ''}">${unitVisual(unit, true)}<figcaption><span>${unit.name}</span><span>${unit.imageCaption}</span></figcaption></figure></div></section>
  <section class="unit-services section" id="solucoes"><div class="wrap services-grid"><div class="services-intro">${eyebrow(unit.slug === 'safek' ? 'Cómo funciona' : 'Lo que hacemos')}<h2 class="display reveal">${unit.heading}</h2><p>${unit.intro}</p></div><ol class="service-list">${unit.services.map(([title, description], i) => `<li class="reveal"><span class="service-number">0${i + 1}</span><div><h3>${title}</h3><p>${description}</p></div></li>`).join('')}</ol></div>${unit.secondaryImage ? `<figure class="detail-photo wrap reveal">${photo(unit.secondaryImage, unit.secondaryAlt, { sizes: '(min-width: 960px) 80vw, 100vw' })}<figcaption>${unit.secondaryAlt}</figcaption></figure>` : ''}</section>
  <section class="unit-cta section"><div class="wrap">${eyebrow('Encuentra tu próxima posibilidad')}<h2 class="display reveal">${unit.cta}</h2>${button(unit.contactLabel, '#contato')}</div></section>
  <aside class="next-unit wrap"><span class="small-label">SIGUE EXPLORANDO EL GRUPO</span><a href="/es/${next.slug}/"><span>${next.name}<small>${next.category}</small></span>${arrow(true)}</a></aside>`;
  await page(`/es/${unit.slug}/`, layout({ title: `${unit.name} — ${unit.category} | GlobalK`, description: unit.seo, path: `/${unit.slug}/`, current: unit.slug, content, locale: 'es' }));
}

const historyContentEs = `<section class="history-hero wrap"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/es/">Inicio</a><span aria-hidden="true">/</span><span aria-current="page">Nuestra historia</span></nav>${eyebrow('Nuestra trayectoria')}<h1 class="display">Nuevos caminos.<br>La misma voluntad de <em>conectar.</em></h1><p>Cada etapa abrió espacio para la siguiente. Descubre los hitos que construyeron GlobalK y sus unidades de negocio.</p><a class="text-link" href="#trajetoria">Recorre nuestra historia <span aria-hidden="true">↓</span></a><div class="history-hero-mark" aria-hidden="true">2010<span>→</span>HOY</div></section>
<section class="timeline-section section" id="trajetoria"><div class="wrap timeline-grid"><div class="timeline-intro">${eyebrow('Una historia en movimiento')}<h2 class="display">Conexiones<br>que se convierten<br>en <em>caminos.</em></h2><p>Desde el desarrollo de marcas hasta las nuevas áreas de actividad del grupo.</p></div><ol class="timeline">${timelineEs.map(item => `<li class="reveal"><span class="timeline-year">${item.year}</span><div><h3>${item.title}</h3><p>${item.text}</p></div></li>`).join('')}</ol></div></section><section class="statement-strip"><div class="wrap"><span class="small-label">EL PRÓXIMO CAPÍTULO SIGUE ABIERTO.</span><p>Construyamos lo que <em>viene después.</em></p><a href="#contato" class="statement-arrow" aria-label="Hablar con GlobalK">${arrow(true)}</a></div></section>`;
await page('/es/our-history/', layout({ title: 'Nuestra historia — Una trayectoria de conexiones | GlobalK', description: 'Descubre la trayectoria de GlobalK, su trabajo con marcas en Brasil y la creación de Economize, Multi-K, Safe-K y Trade-K.', path: '/our-history/', current: 'history', content: historyContentEs, locale: 'es' }));

const notFound = layout({ title: 'Página não encontrada | GlobalK', description: 'Encontre seu caminho de volta para a GlobalK.', path: '/', current: 'error', content: `<section class="error-section wrap">${eyebrow('404 · Página não encontrada')}<h1 class="display">Vamos encontrar<br>outro <em>caminho.</em></h1><p>Esse endereço não está disponível. Explore as unidades de negócio ou volte ao início.</p>${button('Voltar ao início', '/')}${button('Conhecer as unidades', '/#unidades', true)}</section>` });
await writeFile(new URL('404.html', out), notFound);
const paths = ['/', ...units.map(u => `/${u.slug}/`), '/our-history/', '/en/', ...unitsEn.map(u => `/en/${u.slug}/`), '/en/our-history/', '/es/', ...unitsEs.map(u => `/es/${u.slug}/`), '/es/our-history/'];
await writeFile(new URL('sitemap.xml', out), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(path => `<url><loc>https://globalk-site.vercel.app${path}</loc></url>`).join('')}</urlset>`);
await writeFile(new URL('robots.txt', out), 'User-agent: *\nAllow: /\n\nSitemap: https://globalk-site.vercel.app/sitemap.xml\n');
const social = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#0c0c0c"/><circle cx="1100" cy="300" r="350" fill="none" stroke="#cc0d0d" stroke-width="2"/><circle cx="1100" cy="300" r="270" fill="none" stroke="#cc0d0d" stroke-width="1"/><circle cx="1100" cy="300" r="190" fill="none" stroke="#cc0d0d" stroke-width="1"/><text x="70" y="100" fill="#f0ece4" font-family="Arial,sans-serif" font-size="38">GlobalK</text><text x="70" y="290" fill="#f0ece4" font-family="Georgia,serif" font-size="89">O mundo se</text><text x="70" y="397" fill="#f04a3c" font-family="Georgia,serif" font-size="89" font-style="italic">conecta aqui.</text><text x="75" y="551" fill="#b8b3ac" font-family="Arial,sans-serif" font-size="23">MARCAS · PRODUTOS · OPERAÇÕES</text></svg>`;
await sharp(Buffer.from(social)).png().toFile(fileURLToPath(new URL('assets/social-card.png', out)));
console.log(`Build concluído: ${paths.length} páginas, 404, sitemap e recursos locais.`);
