export const company = {
  name: 'GlobalK', email: 'globalk@globalk.com.br', phone: '+55 11 3230-5636',
  phoneHref: 'tel:+551132305636',
  address: 'Shopping Panorâmico, Galpão E — Rodovia Raposo Tavares, km 99. Sorocaba, São Paulo.',
  legal: 'GLOBALK TECNOLOGIA INFORMATICA LTDA.', cnpj: '18.228.061/0001-76',
};

export const units = [
  {
    slug: 'globalk', name: 'GlobalK', number: '01', category: 'Entrada no mercado brasileiro',
    summary: 'Estrutura local para marcas que querem chegar mais longe no Brasil.',
    title: 'Um novo mercado.<br>Um parceiro <em>por inteiro.</em>',
    description: 'Da entrada no Brasil à operação do dia a dia: conectamos marcas internacionais a uma estrutura local de distribuição, vendas e suporte.',
    seo: 'Operação local, distribuição, vendas e suporte para marcas internacionais que querem entrar no mercado brasileiro. Conheça a GlobalK.',
    image: 'tradek', alt: 'Contêineres em uma operação logística, imagem ilustrativa de comércio internacional',
    imageCaption: 'Conexões internacionais. Operação no Brasil.',
    audience: 'Para marcas internacionais que buscam desenvolver sua presença no Brasil com um parceiro local.',
    heading: 'Sua marca no Brasil.<br>Uma operação <em>conectada.</em>',
    intro: 'Reunimos as etapas da operação para aproximar produtos, canais de venda e consumidores. Uma estrutura integrada, com base em Sorocaba.',
    services: [
      ['Entrada no mercado', 'Apoio à estruturação do negócio e aos requisitos de operação no Brasil.'],
      ['Logística e distribuição', 'Organização da operação local e distribuição a partir de Sorocaba.'],
      ['Canais de venda', 'Atuação em marketplaces, e-commerce e loja física.'],
      ['Produtos e marcas', 'Desenvolvimento de produtos e revitalização de marcas para o mercado local.'],
      ['Pós-venda', 'Suporte ao consumidor integrado à operação comercial.'],
    ],
    cta: 'Vamos conversar sobre sua operação?', contactLabel: 'Falar sobre entrada no Brasil',
  },
  {
    slug: 'economize', name: 'Economize', number: '02', category: 'Open Box & varejo',
    summary: 'Novas possibilidades para produtos. Mais escolhas para quem compra.',
    title: 'Boas escolhas.<br>Novas <em>possibilidades.</em>',
    description: 'Produtos Open Box e novos, selecionados e avaliados para voltar ao mercado. A Economize conecta oportunidades de compra a uma operação de varejo multicanal.',
    seo: 'Conheça a Economize, unidade do grupo GlobalK dedicada a produtos Open Box, varejo e operação de marketplaces.',
    image: 'economize', alt: 'Profissional conferindo produtos em um estoque, imagem publicada pela Economize',
    imageCaption: 'Seleção, organização e uma nova oportunidade.',
    audience: 'Para quem procura oportunidades de compra e para empresas interessadas em operação comercial e marketplaces.',
    heading: 'Valor que continua.<br>Consumo que <em>faz sentido.</em>',
    intro: 'Produtos Open Box podem incluir itens devolvidos ou com embalagem aberta. A avaliação e as informações de cada oferta ajudam o consumidor a escolher com clareza.',
    services: [
      ['Produtos Open Box', 'Seleção e controle de qualidade, com informações sobre a condição de cada produto.'],
      ['Varejo multicanal', 'Presença em e-commerce, loja física e marketplaces.'],
      ['Operação comercial', 'Gestão de estoque, precificação e atendimento para operações de venda online.'],
    ],
    external: 'https://economize.vc/', externalLabel: 'Conhecer a loja',
    cta: 'Uma oportunidade para o seu negócio.', contactLabel: 'Falar sobre parcerias',
  },
  {
    slug: 'multik', name: 'Multi-K', number: '03', category: 'Organização & utilidades',
    summary: 'Soluções simples para organizar o que faz parte do seu dia.',
    title: 'Pequenos detalhes.<br>Um dia mais <em>simples.</em>',
    description: 'Organizadores, identificadores e soluções práticas que colocam cada coisa no seu lugar. Funcionalidade para a casa, o trabalho e a rotina.',
    seo: 'Multi-K: organizadores de cabos, identificadores e utilidades para casa e escritório. Conheça os produtos do grupo GlobalK.',
    image: 'multik', alt: 'Organizador de cabos Multi-K em uma mesa de trabalho',
    imageCaption: 'Design que encontra lugar na sua rotina.',
    audience: 'Para pessoas e empresas que procuram organização prática em casa, no escritório ou no dia a dia.',
    heading: 'Menos bagunça.<br>Mais espaço para <em>viver.</em>',
    intro: 'Criamos soluções de organização que combinam utilidade e atenção aos detalhes. Produtos pensados para resolver pequenas necessidades que fazem diferença na rotina.',
    services: [
      ['Organizar', 'Organizadores de cabos para manter acessórios reunidos e o ambiente em ordem.'],
      ['Identificar', 'Identificadores que facilitam reconhecer e separar cabos e objetos.'],
      ['Simplificar', 'Utilidades e soluções de armazenamento para aproveitar melhor os espaços.'],
    ],
    secondaryImage: 'multik-detail', secondaryAlt: 'Aplicações dos organizadores Multi-K',
    cta: 'Vamos colocar boas ideias em prática?', contactLabel: 'Conhecer os produtos',
  },
  {
    slug: 'safek', name: 'Safe-K', number: '04', category: 'Foco & presença',
    summary: 'Ambientes livres de celulares, com o aparelho sempre com seu dono.',
    title: 'Menos distrações.<br>Mais <em>presença.</em>',
    description: 'Uma bolsa com sistema de bloqueio que ajuda a criar ambientes livres de celulares. O aparelho permanece com a pessoa durante toda a experiência.',
    seo: 'Safe-K: bolsas com bloqueio para criar ambientes livres de celulares em escolas, eventos e empresas, mantendo o aparelho com seu dono.',
    image: 'safek', alt: 'Bolsa Safe-K preta com sistema de bloqueio para celular',
    imageCaption: 'O celular com você. A atenção no presente.',
    audience: 'Para escolas, universidades, empresas e eventos que valorizam atenção, convivência e participação.',
    heading: 'O celular fica.<br>A distração <em>vai embora.</em>',
    intro: 'O funcionamento é simples: guardar, bloquear e liberar em uma área apropriada. Uma forma de organizar o uso de celulares sem recolher os aparelhos.',
    services: [
      ['Guardar', 'Na chegada, o celular é colocado dentro da bolsa Safe-K.'],
      ['Bloquear', 'A bolsa é fechada e permanece com seu dono durante a atividade.'],
      ['Liberar', 'Na área indicada, uma base de desbloqueio permite acessar o aparelho.'],
    ],
    external: 'https://safek.com.br/', externalLabel: 'Explorar a Safe-K',
    cta: 'Mais presença começa com uma conversa.', contactLabel: 'Falar sobre a Safe-K',
  },
  {
    slug: 'tradek', name: 'Trade-K', number: '05', category: 'Importação & financiamento',
    summary: 'Uma conexão entre empresas brasileiras e oportunidades na Ásia.',
    title: 'O mundo mais perto.<br>Seu negócio mais <em>longe.</em>',
    description: 'Apoio à compra internacional de mercadorias e soluções de financiamento para empresas brasileiras que importam da Ásia.',
    seo: 'Trade-K: apoio à importação e soluções de financiamento de compras internacionais para empresas brasileiras. Uma unidade do grupo GlobalK.',
    image: 'tradek', alt: 'Contêineres em um terminal de cargas, imagem ilustrativa de importação',
    imageCaption: 'Da oportunidade internacional à operação local.',
    audience: 'Para empresas brasileiras que querem planejar suas compras internacionais e avaliar alternativas de financiamento.',
    heading: 'Importar com visão.<br>Crescer com <em>planejamento.</em>',
    intro: 'A Trade-K conecta a estratégia de compra às necessidades da operação. O projeto e as condições são avaliados de acordo com a realidade de cada negócio.',
    services: [
      ['Compra internacional', 'Suporte ao planejamento e à jornada de aquisição de mercadorias na Ásia.'],
      ['Financiamento', 'Avaliação de soluções para financiar compras e organizar o uso do capital de giro.'],
      ['Acompanhamento', 'Apoio ao longo do processo para dar mais clareza às decisões de importação.'],
    ],
    cta: 'Sua próxima conexão começa aqui.', contactLabel: 'Conversar sobre importação',
  },
];

export const timeline = [
  { year: '2010—12', title: 'O começo de uma conexão.', text: 'Estruturação do negócio, estudos de mercado e primeiras negociações estratégicas.' },
  { year: '2013', title: 'Novos caminhos com a Compaq.', text: 'Acordo de licenciamento da marca Compaq com a HP para produção de computadores e tablets no Brasil.' },
  { year: '2016', title: 'Uma presença em Sorocaba.', text: 'Abertura da primeira loja oficial, com foco em produtos HP recondicionados.' },
  { year: '2020', title: 'Uma nova etapa para a Compaq.', text: 'A trajetória da marca no Brasil passa por uma nova fase com a Positivo Tecnologia.' },
  { year: '2023', title: 'Nasce a Economize.', text: 'Lançamento da plataforma de produtos novos e Open Box, ampliando a atuação no varejo.' },
  { year: '2024', title: 'Organizar também é inovar.', text: 'Criação da Multi-K, com soluções de organização e utilidades para o dia a dia.' },
  { year: '2025', title: 'Mais frentes. A mesma visão.', text: 'Safe-K e Trade-K ampliam o grupo com soluções para ambientes livres de celulares e apoio à importação.' },
];
